"""
BridgeLab Toolkit
Acronym Generator
"""

from __future__ import annotations

from collections import defaultdict

from .base_generator import BaseGenerator


class AcronymGenerator(BaseGenerator):
    """
    Generates acronyms.md.
    """

    # =========================================================
    # Generate
    # =========================================================

    def generate(self) -> str:

        groups = defaultdict(list)

        # -----------------------------------------------------
        # Collect Acronyms
        # -----------------------------------------------------

        for article in self.articles:

            for alias in article.metadata.aliases:

                alias = alias.strip()

                if not alias:
                    continue

                # Keep only likely acronyms
                if not alias.isupper():
                    continue

                letter = alias[0]

                groups[letter].append(

                    (

                        alias,

                        article.metadata.title,

                    )

                )

        # -----------------------------------------------------
        # Markdown
        # -----------------------------------------------------

        lines = []

        lines.append("# Acronyms")

        lines.append("")

        lines.append(
            "Automatically generated by the BridgeLab Toolkit."
        )

        lines.append("")

        for letter in sorted(groups):

            lines.append(f"## {letter}")

            lines.append("")

            for acronym, title in sorted(groups[letter]):

                lines.append(

                    f"- **{acronym}** — {title}"

                )

            lines.append("")

        return "\n".join(lines)
