"""
BridgeLab Toolkit
Bibliography Generator
"""

from __future__ import annotations

from collections import defaultdict

from .base_generator import BaseGenerator


class BibliographyGenerator(BaseGenerator):
    """
    Generates bibliography.md.
    """

    # =========================================================
    # Generate
    # =========================================================

    def generate(self) -> str:

        references = defaultdict(set)

        # -----------------------------------------------------
        # Collect References
        # -----------------------------------------------------

        for article in self.articles:

            for reference in article.metadata.references:

                reference = reference.strip()

                if not reference:
                    continue

                letter = reference[0].upper()

                references[letter].add(reference)

        # -----------------------------------------------------
        # Markdown
        # -----------------------------------------------------

        lines = []

        lines.append("# Bibliography")

        lines.append("")

        lines.append(
            "Automatically generated by the BridgeLab Toolkit."
        )

        lines.append("")

        for letter in sorted(references):

            lines.append(f"## {letter}")

            lines.append("")

            for reference in sorted(references[letter]):

                lines.append(f"- {reference}")

            lines.append("")

        return "\n".join(lines)
