"""
BridgeLab Toolkit
Document Writer
"""

from __future__ import annotations

from pathlib import Path


class DocumentWriter:
    """
    Writes generated BridgeLab documents.
    """

    HEADER = (
        "<!--\n"
        "Automatically generated by the BridgeLab Toolkit.\n"
        "Do not edit manually.\n"
        "-->\n\n"
    )

    # =========================================================
    # Write
    # =========================================================

    def write(

        self,

        output: Path,

        content: str,

    ):

        output.parent.mkdir(

            parents=True,

            exist_ok=True,

        )

        output.write_text(

            self.HEADER + content,

            encoding="utf-8",

        )

    # =========================================================
    # Append
    # =========================================================

    def append(

        self,

        output: Path,

        content: str,

    ):

        output.parent.mkdir(

            parents=True,

            exist_ok=True,

        )

        with output.open(

            "a",

            encoding="utf-8",

        ) as file:

            file.write(content)
