"""
BridgeLab Toolkit
Glossary Builder
"""

from __future__ import annotations

from collections import defaultdict

from core.models import Entity


class GlossaryBuilder:
    """
    Builds a glossary from extracted entities.
    """

    # =========================================================
    # Build
    # =========================================================

    def build(
        self,
        entities: list[Entity],
    ) -> str:

        groups = defaultdict(list)

        # -----------------------------------------------------
        # Group entities alphabetically
        # -----------------------------------------------------

        for entity in entities:

            if not entity.name:

                continue

            letter = entity.name[0].upper()

            groups[letter].append(entity)

        # -----------------------------------------------------
        # Markdown
        # -----------------------------------------------------

        lines = []

        lines.append("# Glossary")

        lines.append("")

        lines.append(
            "Automatically generated by the BridgeLab Toolkit."
        )

        lines.append("")

        for letter in sorted(groups):

            lines.append(f"## {letter}")

            lines.append("")

            section = sorted(

                groups[letter],

                key=lambda entity: entity.name.lower(),

            )

            for entity in section:

                lines.append(

                    f"### {entity.name}"

                )

                lines.append("")

                lines.append(

                    f"- Category: {entity.category}"

                )

                lines.append(

                    f"- Article: {entity.article}"

                )

                lines.append("")

        return "\n".join(lines)
