"""Auction-time information available to one player.

This module consumes *interpreted* constraints. It does not interpret bids,
inspect unseen hands, or estimate the trick value of distribution. In
particular, a promised suit length is evidence about a hand, not knowledge of
the identity of any of its cards (as required by ``vacant_places``).
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from fractions import Fraction
from typing import Iterable

from .auction import Auction, AuctionEntry, Call
from .evaluation import SUIT_ORDER, high_card_points
from .models import Hand, Seat, Suit
from .probability_values import ProbabilityValue


class Certainty(Enum):
    EXACT = "exact"
    GUARANTEED = "guaranteed"
    INFERRED = "inferred"
    PROBABILISTIC = "probabilistic"
    UNKNOWN = "unknown"


class EvidenceOrigin(Enum):
    OWN_HAND = "own_hand"
    PARTNER_CALL = "partner_call"
    OPPONENT_CALL = "opponent_call"
    PROFILE_INTERPRETATION = "profile_interpretation"
    DERIVED_ARITHMETIC = "derived_arithmetic"
    VACANT_PLACE = "vacant_place"
    COMBINED_EVIDENCE = "combined_evidence"
    NEGATIVE_INFERENCE = "negative_inference"


class InformationStatus(Enum):
    CONSISTENT = "consistent"
    CONTRADICTORY = "contradictory"


class FitStatus(Enum):
    NO_FIT_EVIDENCE = "no_fit_evidence"
    POSSIBLE_FIT = "possible_fit"
    NO_POSSIBLE_FIT = "no_possible_fit"
    CONTRADICTORY = "contradictory"
    KNOWN_8_PLUS_FIT = "known_8_plus_fit"
    KNOWN_9_PLUS_FIT = "known_9_plus_fit"
    KNOWN_10_PLUS_FIT = "known_10_plus_fit"


class ShortnessKind(Enum):
    VOID = "void"
    SINGLETON = "singleton"
    DOUBLETON = "doubleton"


@dataclass(frozen=True, slots=True)
class NumericRange:
    minimum: int
    maximum: int

    def __post_init__(self) -> None:
        if any(not isinstance(x, int) or isinstance(x, bool) for x in (self.minimum, self.maximum)):
            raise TypeError("range endpoints must be integers")
        if self.minimum < 0 or self.minimum > self.maximum:
            raise ValueError("range must be nonnegative and ordered")

    def intersect(self, other: NumericRange) -> NumericRange | None:
        low, high = max(self.minimum, other.minimum), min(self.maximum, other.maximum)
        return NumericRange(low, high) if low <= high else None


@dataclass(frozen=True, slots=True)
class ConstraintProvenance:
    origin: EvidenceOrigin
    reference: str
    call_index: int | None = None
    source_id: str | None = None

    def __post_init__(self) -> None:
        if not isinstance(self.origin, EvidenceOrigin):
            raise TypeError("origin must be EvidenceOrigin")
        if not isinstance(self.reference, str) or not self.reference.strip():
            raise ValueError("reference must identify the evidence")
        if self.call_index is not None and (not isinstance(self.call_index, int) or isinstance(self.call_index, bool) or self.call_index < 0):
            raise ValueError("call_index must be a nonnegative integer")
        if self.source_id is not None and (not isinstance(self.source_id, str) or not self.source_id.strip()):
            raise ValueError("source_id must be a nonempty string")


@dataclass(frozen=True, slots=True)
class DiscreteDistribution:
    """A supplied distribution. No probabilities are generated by PT-A0."""

    outcomes: tuple[tuple[int, ProbabilityValue], ...]

    def __post_init__(self) -> None:
        if not isinstance(self.outcomes, tuple) or any(not isinstance(item, tuple) or len(item) != 2 for item in self.outcomes):
            raise TypeError("distribution outcomes must be immutable pairs")
        if not self.outcomes or len({value for value, _ in self.outcomes}) != len(self.outcomes):
            raise ValueError("distribution needs unique outcomes")
        if any(not isinstance(value, int) or isinstance(value, bool) or value < 0 or
               not isinstance(probability, ProbabilityValue)
               for value, probability in self.outcomes):
            raise ValueError("invalid distribution outcome")
        if sum((probability.as_fraction() for _, probability in self.outcomes), Fraction()) != 1:
            raise ValueError("distribution probabilities must sum to one")


@dataclass(frozen=True, slots=True)
class RangeEvidence:
    bounds: NumericRange
    certainty: Certainty
    provenance: ConstraintProvenance
    distribution: DiscreteDistribution | None = None

    def __post_init__(self) -> None:
        if not isinstance(self.bounds, NumericRange) or not isinstance(self.certainty, Certainty) or not isinstance(self.provenance, ConstraintProvenance):
            raise TypeError("range evidence needs typed bounds, certainty, and provenance")
        if self.certainty is Certainty.UNKNOWN:
            raise ValueError("unknown is represented by absence of evidence")
        if self.certainty is Certainty.EXACT and self.bounds.minimum != self.bounds.maximum:
            raise ValueError("exact range evidence must name one value")
        if self.distribution is not None:
            if self.certainty is not Certainty.PROBABILISTIC or not isinstance(self.distribution, DiscreteDistribution):
                raise ValueError("distribution requires probabilistic evidence")
            if any(not self.bounds.minimum <= value <= self.bounds.maximum for value, _ in self.distribution.outcomes):
                raise ValueError("distribution support must lie within stated bounds")

    @property
    def is_hard(self) -> bool:
        return self.certainty in (Certainty.EXACT, Certainty.GUARANTEED)


@dataclass(frozen=True, slots=True)
class ShapeEvidence:
    """Allowed 13-card shapes in S.H.D.C order."""

    allowed: tuple[tuple[int, int, int, int], ...]
    certainty: Certainty
    provenance: ConstraintProvenance

    def __post_init__(self) -> None:
        if not isinstance(self.allowed, tuple) or any(not isinstance(shape, tuple) for shape in self.allowed):
            raise TypeError("allowed shapes must be immutable tuples")
        if not isinstance(self.certainty, Certainty) or not isinstance(self.provenance, ConstraintProvenance):
            raise TypeError("shape evidence needs typed certainty and provenance")
        if not self.allowed or len(set(self.allowed)) != len(self.allowed):
            raise ValueError("shape evidence requires distinct allowed shapes")
        if any(len(shape) != 4 or any(not isinstance(n, int) or isinstance(n, bool) or n < 0 for n in shape) or sum(shape) != 13 for shape in self.allowed):
            raise ValueError("each shape must contain 13 cards in S.H.D.C order")
        if self.certainty is Certainty.UNKNOWN:
            raise ValueError("unknown is represented by absence of evidence")
        if self.certainty is Certainty.EXACT and len(self.allowed) != 1:
            raise ValueError("exact shape evidence must name one shape")

    @property
    def is_hard(self) -> bool:
        return self.certainty in (Certainty.EXACT, Certainty.GUARANTEED)


@dataclass(frozen=True, slots=True)
class AuctionConstraintUpdate:
    """Resolved meaning supplied by an external auction/profile interpreter."""

    target: Seat
    hcp: RangeEvidence | None = None
    suit_lengths: tuple[tuple[Suit, RangeEvidence], ...] = ()
    shapes: ShapeEvidence | None = None

    def __post_init__(self) -> None:
        if not isinstance(self.target, Seat):
            raise TypeError("target must be Seat")
        if not isinstance(self.suit_lengths, tuple) or any(not isinstance(item, tuple) or len(item) != 2 for item in self.suit_lengths):
            raise TypeError("suit lengths must be immutable pairs")
        if self.hcp is not None and (not isinstance(self.hcp, RangeEvidence) or self.hcp.bounds.maximum > 40):
            raise ValueError("HCP evidence must be within 0..40")
        if any(not isinstance(suit, Suit) or not isinstance(evidence, RangeEvidence) or evidence.bounds.maximum > 13
               for suit, evidence in self.suit_lengths):
            raise ValueError("suit evidence must be within 0..13")
        if len({suit for suit, _ in self.suit_lengths}) != len(self.suit_lengths):
            raise ValueError("each update may constrain a suit only once")
        if self.shapes is not None and not isinstance(self.shapes, ShapeEvidence):
            raise TypeError("shapes must be ShapeEvidence")
        if self.hcp is None and not self.suit_lengths and self.shapes is None:
            raise ValueError("update must contain evidence")

    @property
    def provenance(self) -> tuple[ConstraintProvenance, ...]:
        parts = ([self.hcp.provenance] if self.hcp is not None else [])
        parts += [evidence.provenance for _, evidence in self.suit_lengths]
        if self.shapes is not None:
            parts.append(self.shapes.provenance)
        return tuple(parts)


@dataclass(frozen=True, slots=True)
class ConstraintConflict:
    subject: str
    sources: tuple[ConstraintProvenance, ...]


@dataclass(frozen=True, slots=True)
class SeatInformation:
    """Hard range projections; soft evidence remains in ``evidence`` unchanged.

    A singleton hard range is logically guaranteed, not an observed hidden hand.
    These are per-seat projections, not a joint distribution of unseen hands.
    """

    seat: Seat
    hcp: NumericRange | None
    suit_lengths: tuple[tuple[Suit, NumericRange | None], ...]
    possible_shapes: tuple[tuple[int, int, int, int], ...]
    evidence: tuple[AuctionConstraintUpdate, ...]
    conflicts: tuple[ConstraintConflict, ...]

    @property
    def status(self) -> InformationStatus:
        return InformationStatus.CONTRADICTORY if self.conflicts else InformationStatus.CONSISTENT

    def suit_range(self, suit: Suit) -> NumericRange | None:
        return dict(self.suit_lengths)[suit]

    def suit_evidence(self, suit: Suit) -> tuple[RangeEvidence, ...]:
        return tuple(evidence for update in self.evidence for known_suit, evidence in update.suit_lengths if known_suit is suit)

    def hcp_evidence(self) -> tuple[RangeEvidence, ...]:
        return tuple(update.hcp for update in self.evidence if update.hcp is not None)

    def hcp_provenance(self) -> tuple[ConstraintProvenance, ...]:
        """Sources behind the hard HCP range, including visible-deck arithmetic."""
        sources = tuple(e.provenance for e in self.hcp_evidence() if e.is_hard)
        return sources + (ConstraintProvenance(EvidenceOrigin.DERIVED_ARITHMETIC, "40 minus visible HCP"),)

    def suit_provenance(self, suit: Suit) -> tuple[ConstraintProvenance, ...]:
        """Sources relevant to a suit bound, including 13-card shape deductions."""
        direct = tuple(e.provenance for e in self.suit_evidence(suit) if e.is_hard)
        other_suits = tuple(e.provenance for update in self.evidence for _, e in update.suit_lengths if e.is_hard)
        shapes = tuple(update.shapes.provenance for update in self.evidence if update.shapes is not None and update.shapes.is_hard)
        return tuple(dict.fromkeys(direct + other_suits + shapes + (
            ConstraintProvenance(EvidenceOrigin.DERIVED_ARITHMETIC, "13-card shape and visible suit cards"),)))

    def shortness_possible(self, suit: Suit, kind: ShortnessKind) -> bool:
        length = {ShortnessKind.VOID: 0, ShortnessKind.SINGLETON: 1, ShortnessKind.DOUBLETON: 2}[kind]
        bounds = self.suit_range(suit)
        return bounds is not None and bounds.minimum <= length <= bounds.maximum

    def shortness_known(self, suit: Suit, kind: ShortnessKind) -> bool:
        length = {ShortnessKind.VOID: 0, ShortnessKind.SINGLETON: 1, ShortnessKind.DOUBLETON: 2}[kind]
        bounds = self.suit_range(suit)
        return bounds is not None and bounds.minimum == bounds.maximum == length


@dataclass(frozen=True, slots=True)
class FitInformation:
    suit: Suit
    own_length: int
    other_length: NumericRange | None
    total: NumericRange | None
    status: FitStatus
    sources: tuple[ConstraintProvenance, ...]


@dataclass(frozen=True, slots=True)
class OpponentFitInformation:
    suit: Suit
    left_length: NumericRange | None
    right_length: NumericRange | None
    total: NumericRange | None
    status: FitStatus
    sources: tuple[ConstraintProvenance, ...]


@dataclass(frozen=True, slots=True)
class ShortnessInformation:
    suit: Suit
    length: int
    kind: ShortnessKind
    certainty: Certainty
    provenance: ConstraintProvenance
    fit_established: bool
    partner_information_available: bool
    opponent_location_evidence_available: bool


def _hard(evidence: RangeEvidence | ShapeEvidence) -> bool:
    return evidence.certainty in (Certainty.EXACT, Certainty.GUARANTEED)


def _fit_status(total: NumericRange | None, has_evidence: bool) -> FitStatus:
    if total is None:
        return FitStatus.CONTRADICTORY
    if total.minimum >= 10:
        return FitStatus.KNOWN_10_PLUS_FIT
    if total.minimum >= 9:
        return FitStatus.KNOWN_9_PLUS_FIT
    if total.minimum >= 8:
        return FitStatus.KNOWN_8_PLUS_FIT
    if total.maximum < 8:
        return FitStatus.NO_POSSIBLE_FIT
    return FitStatus.POSSIBLE_FIT if has_evidence else FitStatus.NO_FIT_EVIDENCE


@dataclass(frozen=True, slots=True)
class AuctionInformationState:
    perspective: Seat
    dealer: Seat
    own_hand: Hand
    entries: tuple[AuctionEntry, ...] = ()
    updates: tuple[AuctionConstraintUpdate, ...] = ()

    def __post_init__(self) -> None:
        if not isinstance(self.perspective, Seat) or not isinstance(self.dealer, Seat) or not isinstance(self.own_hand, Hand):
            raise TypeError("state requires perspective, dealer, and exact own Hand")
        if not isinstance(self.entries, tuple) or not isinstance(self.updates, tuple):
            raise TypeError("entries and updates must be immutable tuples")
        auction = Auction(self.dealer)
        for entry in self.entries:
            if not isinstance(entry, AuctionEntry) or auction.add(entry.call) != entry:
                raise ValueError("entries must be a legal auction in dealer order")
        for update in self.updates:
            if not isinstance(update, AuctionConstraintUpdate) or update.target is self.perspective:
                raise ValueError("updates must target an unknown seat")
            for evidence in ([update.hcp] if update.hcp is not None else []) + [e for _, e in update.suit_lengths] + ([update.shapes] if update.shapes is not None else []):
                if evidence.certainty is Certainty.EXACT:
                    raise ValueError("exact unknown-seat information is outside auction-time scope")
            for provenance in update.provenance:
                index = provenance.call_index
                if index is not None and index >= len(self.entries):
                    raise ValueError("provenance cannot refer to a future call")
                if provenance.origin in (EvidenceOrigin.PARTNER_CALL, EvidenceOrigin.OPPONENT_CALL):
                    if index is None:
                        raise ValueError("call evidence requires a call_index")
                    actor = self.entries[index].seat
                    expected = self.perspective.partner() if provenance.origin is EvidenceOrigin.PARTNER_CALL else None
                    if (expected is not None and actor is not expected) or (expected is None and actor in (self.perspective, self.perspective.partner())):
                        raise ValueError("call provenance actor does not match its origin")

    @classmethod
    def start(cls, perspective: Seat, own_hand: Hand, dealer: Seat) -> AuctionInformationState:
        return cls(perspective, dealer, own_hand)

    @classmethod
    def from_auction(cls, perspective: Seat, own_hand: Hand, auction: Auction,
                     updates: Iterable[AuctionConstraintUpdate] = ()) -> AuctionInformationState:
        if not isinstance(auction, Auction):
            raise TypeError("auction must be Auction")
        return cls(perspective, auction.dealer, own_hand, auction.entries, tuple(updates))

    def after_call(self, call: Call | str, updates: Iterable[AuctionConstraintUpdate] = ()) -> AuctionInformationState:
        auction = Auction(self.dealer, (entry.call for entry in self.entries))
        entry = auction.add(call)
        return AuctionInformationState(self.perspective, self.dealer, self.own_hand,
                                       self.entries + (entry,), self.updates + tuple(updates))

    def with_updates(self, updates: Iterable[AuctionConstraintUpdate]) -> AuctionInformationState:
        return AuctionInformationState(self.perspective, self.dealer, self.own_hand,
                                       self.entries, self.updates + tuple(updates))

    @property
    def partner(self) -> Seat:
        return self.perspective.partner()

    @property
    def opponents(self) -> tuple[Seat, Seat]:
        return self.perspective.next(), self.partner.next()

    def for_seat(self, seat: Seat) -> SeatInformation:
        if not isinstance(seat, Seat) or seat is self.perspective:
            raise ValueError("for_seat requires an unknown seat")
        relevant = tuple(update for update in self.updates if update.target is seat)
        own_hcp = high_card_points(self.own_hand)
        hcp_base = NumericRange(0, 40 - own_hcp)
        hcp_sources = [update.hcp for update in relevant if update.hcp is not None and _hard(update.hcp)]
        hcp = hcp_base
        conflicts: list[ConstraintConflict] = []
        for evidence in hcp_sources:
            if hcp is not None:
                hcp = hcp.intersect(evidence.bounds)
        if hcp is None:
            conflicts.append(ConstraintConflict("HCP", tuple(e.provenance for e in hcp_sources) +
                                                (ConstraintProvenance(EvidenceOrigin.DERIVED_ARITHMETIC, "40 minus visible HCP"),)))

        raw_suits: dict[Suit, NumericRange | None] = {}
        for suit in SUIT_ORDER:
            bound: NumericRange | None = NumericRange(0, 13 - self.own_hand.length(suit))
            sources = [e for update in relevant for known_suit, e in update.suit_lengths if known_suit is suit and _hard(e)]
            for evidence in sources:
                if bound is not None:
                    bound = bound.intersect(evidence.bounds)
            raw_suits[suit] = bound
            if bound is None:
                conflicts.append(ConstraintConflict(f"{suit.letter} length", tuple(e.provenance for e in sources) +
                                                    (ConstraintProvenance(EvidenceOrigin.DERIVED_ARITHMETIC, "13 minus visible suit cards"),)))

        hard_shapes = [update.shapes for update in relevant if update.shapes is not None and _hard(update.shapes)]
        shapes: list[tuple[int, int, int, int]] = []
        if all(bound is not None for bound in raw_suits.values()):
            for spades in range(14):
                for hearts in range(14 - spades):
                    for diamonds in range(14 - spades - hearts):
                        shape = (spades, hearts, diamonds, 13 - spades - hearts - diamonds)
                        if all(raw_suits[suit].minimum <= shape[i] <= raw_suits[suit].maximum for i, suit in enumerate(SUIT_ORDER)) and all(shape in evidence.allowed for evidence in hard_shapes):
                            shapes.append(shape)
        if not shapes and not any(conflict.subject.endswith("length") for conflict in conflicts):
            sources = tuple(e.provenance for update in relevant for _, e in update.suit_lengths if _hard(e))
            sources += tuple(e.provenance for e in hard_shapes)
            conflicts.append(ConstraintConflict("13-card shape", sources +
                                                (ConstraintProvenance(EvidenceOrigin.DERIVED_ARITHMETIC, "13 total cards and visible suit caps"),)))
        suit_bounds = tuple((suit, NumericRange(min(shape[i] for shape in shapes), max(shape[i] for shape in shapes)) if shapes else None)
                            for i, suit in enumerate(SUIT_ORDER))
        return SeatInformation(seat, hcp, suit_bounds, tuple(shapes), relevant, tuple(conflicts))

    @property
    def conflicts(self) -> tuple[ConstraintConflict, ...]:
        info = tuple(self.for_seat(seat) for seat in (self.partner, *self.opponents))
        conflicts = [conflict for seat_info in info for conflict in seat_info.conflicts]
        for suit in SUIT_ORDER:
            bounds = [seat_info.suit_range(suit) for seat_info in info]
            if all(bound is not None for bound in bounds):
                remaining = 13 - self.own_hand.length(suit)
                if sum(bound.minimum for bound in bounds) > remaining or sum(bound.maximum for bound in bounds) < remaining:
                    sources = tuple(dict.fromkeys(provenance for seat_info in info
                                                  for provenance in seat_info.suit_provenance(suit)))
                    conflicts.append(ConstraintConflict(f"unseen {suit.letter} cards", sources +
                                                        (ConstraintProvenance(EvidenceOrigin.DERIVED_ARITHMETIC, "13 cards per suit"),)))
        hcp_bounds = [seat_info.hcp for seat_info in info]
        if all(bound is not None for bound in hcp_bounds):
            remaining = 40 - high_card_points(self.own_hand)
            if sum(bound.minimum for bound in hcp_bounds) > remaining or sum(bound.maximum for bound in hcp_bounds) < remaining:
                sources = tuple(dict.fromkeys(provenance for seat_info in info
                                              for provenance in seat_info.hcp_provenance()))
                conflicts.append(ConstraintConflict("unseen HCP", sources +
                                                    (ConstraintProvenance(EvidenceOrigin.DERIVED_ARITHMETIC, "40 HCP per deck"),)))
        if not conflicts:
            # Preserve correlations within allowed shapes: independent suit
            # extrema alone can miss an impossible combination of three seats.
            remaining_shape = tuple(13 - self.own_hand.length(suit) for suit in SUIT_ORDER)
            first, second, third = sorted((item.possible_shapes for item in info), key=len)
            third_shapes = set(third)
            compatible = any(
                tuple(remaining_shape[i] - a[i] - b[i] for i in range(4)) in third_shapes
                for a in first for b in second)
            if not compatible:
                sources = tuple(dict.fromkeys(
                    provenance for item in info for suit in SUIT_ORDER
                    for provenance in item.suit_provenance(suit)))
                conflicts.append(ConstraintConflict("joint unseen shapes", sources))
        return tuple(conflicts)

    @property
    def status(self) -> InformationStatus:
        return InformationStatus.CONTRADICTORY if self.conflicts else InformationStatus.CONSISTENT

    def fit(self, suit: Suit) -> FitInformation:
        partner = self.for_seat(self.partner)
        other = partner.suit_range(suit)
        own_length = self.own_hand.length(suit)
        total = NumericRange(own_length + other.minimum, own_length + other.maximum) if other else None
        sources = (ConstraintProvenance(EvidenceOrigin.OWN_HAND, "visible own trump length"),)
        sources += partner.suit_provenance(suit)
        baseline = NumericRange(0, 13 - own_length)
        if self.status is InformationStatus.CONTRADICTORY:
            total = None
            status = FitStatus.CONTRADICTORY
        else:
            status = _fit_status(total, other != baseline)
        return FitInformation(suit, own_length, other, total, status, sources)

    def opponent_fit(self, suit: Suit) -> OpponentFitInformation:
        left, right = (self.for_seat(seat) for seat in self.opponents)
        a, b = left.suit_range(suit), right.suit_range(suit)
        partner = self.for_seat(self.partner)
        partner_length = partner.suit_range(suit)
        sources = left.suit_provenance(suit) + right.suit_provenance(suit)
        sources += partner.suit_provenance(suit) + (
            ConstraintProvenance(EvidenceOrigin.OWN_HAND, "visible own suit length"),
            ConstraintProvenance(EvidenceOrigin.DERIVED_ARITHMETIC,
                                 "opponent total = 13 minus partnership length"),)
        remaining = 13 - self.own_hand.length(suit)
        baseline = NumericRange(0, remaining)
        total = None
        if self.status is InformationStatus.CONTRADICTORY:
            status = FitStatus.CONTRADICTORY
        else:
            # Both defenders share the cards left after the partnership holding.
            total = NumericRange(a.minimum + b.minimum, a.maximum + b.maximum).intersect(
                NumericRange(remaining - partner_length.maximum,
                             remaining - partner_length.minimum))
            status = _fit_status(total, a != baseline or b != baseline or partner_length != baseline)
        return OpponentFitInformation(suit, a, b, total, status, sources)

    def own_shortness(self) -> tuple[ShortnessInformation, ...]:
        found: list[ShortnessInformation] = []
        for suit in SUIT_ORDER:
            length = self.own_hand.length(suit)
            if length > 2:
                continue
            kind = (ShortnessKind.VOID, ShortnessKind.SINGLETON, ShortnessKind.DOUBLETON)[length]
            partner_info = self.for_seat(self.partner)
            opponent_evidence = any(update.target in self.opponents and
                                    (any(s is suit for s, _ in update.suit_lengths) or update.shapes is not None)
                                    for update in self.updates)
            found.append(ShortnessInformation(
                suit, length, kind, Certainty.EXACT,
                ConstraintProvenance(EvidenceOrigin.OWN_HAND, "visible own hand"),
                any(self.fit(trump).status in (FitStatus.KNOWN_8_PLUS_FIT, FitStatus.KNOWN_9_PLUS_FIT, FitStatus.KNOWN_10_PLUS_FIT)
                    for trump in SUIT_ORDER if trump is not suit),
                bool(partner_info.evidence), opponent_evidence))
        return tuple(found)


def snapshots(initial: AuctionInformationState,
              steps: Iterable[tuple[Call | str, Iterable[AuctionConstraintUpdate]]]) -> tuple[AuctionInformationState, ...]:
    """Return one immutable, cumulative state after each call."""
    states: list[AuctionInformationState] = []
    current = initial
    for call, updates in steps:
        current = current.after_call(call, updates)
        states.append(current)
    return tuple(states)
